# 固定版本镜像
# ghcr.io/ayaka-notes/texlive-full:2026.1
# postgres:16-alpine
# mysql:8.0
# vaultwarden/server:1.37.1

# 常用小众镜像
vaultwarden/server:latest
amilys/embyserver:latest
calciumion/new-api:latest
eceasy/cli-proxy-api:latest
ghcr.io/xtls/xray-core:latest
jxxghp/moviepilot-v2:latest
kopia/kopia:latest
openlistteam/openlist:latest
snowdreamtech/frpc:latest
yisier1/npc:latest
looplj/axonhub:unstable

# 常用开发镜像
# maven:latest
# redis:latest
# mongo:latest
# postgres:latest
# mysql:latest
# mariadb:latest
# golang:latest
# python:latest
# rabbitmq:latest
# php:latest
# ruby:latest
alpine:latest
ubuntu:latest
nginx:latest
node:latest
debian:latest
