# 常用自定义镜像
vaultwarden/server:latest
vaultwarden/server:testing
amilys/embyserver:latest
calciumion/new-api:latest
eceasy/cli-proxy-api:latest
ghcr.io/xtls/xray-core:latest
jxxghp/moviepilot-v2:latest
kopia/kopia:latest
openlistteam/openlist:latest
snowdreamtech/frpc:latest
yisier1/npc:latest
jonathanpotts/babelfishpg:latest

# 不常用自定义镜像
# ghcr.io/ayaka-notes/texlive-full:2026.1

# 常用主流镜像
alpine:latest
redis:latest
mongo:latest
postgres:latest
ubuntu:latest
busybox:latest
nginx:latest
httpd:latest
node:latest
mysql:latest
traefik:latest
memcached:latest
hello-world:latest
registry:latest
mariadb:latest
docker:latest
golang:latest
python:latest
rabbitmq:latest
php:latest
wordpress:latest
haproxy:latest
influxdb:latest
ruby:latest
debian:latest
nextcloud:latest
tomcat:latest
maven:latest
telegraf:latest
logstash:latest
amazonlinux:latest
ghost:latest