name: Sync Images

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"
      timezone: "Asia/Shanghai"

jobs:
  sync:
    runs-on: 	ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Login Docker Hub
        run: |
          skopeo login docker.io \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Login Private Registry
        run: |
          skopeo login swr.ap-southeast-1.myhuaweicloud.com \
            -u "${{ secrets.REGISTRY_USERNAME }}" \
            -p "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Sync images
        run: |
          chmod +x sync.sh
          ./sync.sh

      - name: Commit checkpoint
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

            git add .

            git diff --cached --quiet || git commit -m "Update sync checkpoint"

            git push